version: '3'
services:
  nodejs:
    build: ./src
    restart: on-failure:3
    ports:
      - "8080:8080"
    env_file:
     - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: on-failure:3
    ports:
      - 27017:27017
    env_file:
      - ./mongo.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./express.env
    depends_on:
      - mongo